// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: New Dysplay

#ifndef UI_THERMOSTAT_3_H
#define UI_THERMOSTAT_3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_THERMOSTAT_3
extern void ui_THERMOSTAT_3_screen_init(void);
extern void ui_THERMOSTAT_3_screen_destroy(void);
extern void ui_THERMOSTAT_3_screen_relocalize(void);
extern lv_obj_t * ui_THERMOSTAT_3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_ALARM;
extern lv_obj_t * ui_MINUS;
extern lv_obj_t * ui_PLUS;
extern lv_obj_t * ui_HEATING;
extern lv_obj_t * ui_LIGHS;
extern lv_obj_t * ui_BLINDS;
extern lv_obj_t * ui_HEAT_PUMP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

