#!/usr/bin/env python3
"""Convert 800x480 PNG to LVGL LV_IMG_CF_TRUE_COLOR (RGB565) C source."""
import os
import struct
import sys

try:
    from PIL import Image
except ImportError:
    print("Install Pillow: pip install Pillow", file=sys.stderr)
    sys.exit(1)

LV_IMG_CF_TRUE_COLOR = 4


def rgb_to_rgb565_le(r: int, g: int, b: int) -> bytes:
    """LVGL lv_color16_t when LV_COLOR_16_SWAP==0: B5 G6 R5, uint16 little-endian."""
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return struct.pack("<H", v)


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    png = os.path.join(root, "ui_reference.png")
    out_c = os.path.join(root, "src", "ui_reference_img.c")
    if len(sys.argv) >= 2:
        png = sys.argv[1]
    if len(sys.argv) >= 3:
        out_c = sys.argv[2]

    im = Image.open(png).convert("RGBA")
    if im.size != (800, 480):
        im = im.resize((800, 480), Image.Resampling.LANCZOS)

    w, h = im.size
    pixels = im.load()
    raw = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if a < 128:
                r, g, b = 0xE8, 0xE8, 0xE8  # light gray bg if transparent
            raw.extend(rgb_to_rgb565_le(r, g, b))

    data_size = len(raw)
    var = "ui_reference_img_map"

    lines = [
        "/* Auto-generated by scripts/png_to_lvgl_true_color.py — do not edit by hand */",
        '#include "lvgl.h"',
        "",
        "#if LV_COLOR_DEPTH != 16",
        '#error "ui_reference_img requires LV_COLOR_DEPTH == 16"',
        "#endif",
        "",
        f"static const uint8_t {var}[] __attribute__((aligned(4))) = {{",
    ]
    # chunk hex lines
    row_bytes = w * 2
    for i in range(0, len(raw), 16):
        chunk = raw[i : i + 16]
        hexs = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hexs},")
    lines.append("};")
    lines.append("")
    lines.append("const lv_img_dsc_t ui_reference_img = {")
    lines.append("    .header = {")
    lines.append(f"        .cf = {LV_IMG_CF_TRUE_COLOR},")
    lines.append("        .always_zero = 0,")
    lines.append("        .reserved = 0,")
    lines.append(f"        .w = {w},")
    lines.append(f"        .h = {h},")
    lines.append("    },")
    lines.append(f"    .data_size = {data_size},")
    lines.append(f"    .data = {var},")
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(out_c), exist_ok=True)
    with open(out_c, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_c} ({data_size} bytes image data)")


if __name__ == "__main__":
    main()
