# Convert PNG to LVGL LV_IMG_CF_TRUE_COLOR (RGB565) C source (same logic as png_to_lvgl_true_color.py)
param(
    [string]$Png = (Join-Path (Split-Path $PSScriptRoot -Parent) "ui_reference.png"),
    [string]$OutC = (Join-Path (Split-Path $PSScriptRoot -Parent) "src\ui_reference_img.c")
)

Add-Type -AssemblyName System.Drawing

$w = 800
$h = 480
$src = [System.Drawing.Bitmap]::FromFile((Resolve-Path $Png))
try {
    $dst = New-Object System.Drawing.Bitmap $w, $h
    $gfx = [System.Drawing.Graphics]::FromImage($dst)
    try {
        $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $gfx.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $gfx.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $gfx.DrawImage($src, 0, 0, $w, $h)
    } finally {
        $gfx.Dispose()
    }

    $raw = New-Object System.Collections.Generic.List[byte]
    for ($yy = 0; $yy -lt $h; $yy++) {
        for ($xx = 0; $xx -lt $w; $xx++) {
            $c = $dst.GetPixel($xx, $yy)
            $r = [int]$c.R; $gg = [int]$c.G; $bb = [int]$c.B; $a = [int]$c.A
            if ($a -lt 128) { $r = 0xE8; $gg = 0xE8; $bb = 0xE8 }
            $v = ((($r -shr 3) -shl 11) -bor (($gg -shr 2) -shl 5) -bor ($bb -shr 3))
            [void]$raw.Add([byte]($v -band 0xFF))
            [void]$raw.Add([byte](($v -shr 8) -band 0xFF))
        }
    }
    $dst.Dispose()
} finally {
    $src.Dispose()
}

$dataSize = $raw.Count
$varName = "ui_reference_img_map"
$cf = 4

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* Auto-generated by scripts/png_to_lvgl_true_color.ps1 - do not edit by hand */')
[void]$sb.AppendLine('#include "lvgl.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#if LV_COLOR_DEPTH != 16')
[void]$sb.AppendLine('#error "ui_reference_img requires LV_COLOR_DEPTH == 16"')
[void]$sb.AppendLine('#endif')
[void]$sb.AppendLine('')
[void]$sb.AppendLine(('static const uint8_t {0}[] __attribute__((aligned(4))) = {{' -f $varName))

for ($i = 0; $i -lt $raw.Count; $i += 16) {
    $n = [Math]::Min(16, $raw.Count - $i)
    $parts = New-Object string[] $n
    for ($j = 0; $j -lt $n; $j++) {
        $parts[$j] = ('0x{0:x2}' -f $raw[$i + $j])
    }
    $hex = $parts -join ', '
    [void]$sb.AppendLine(('    {0},' -f $hex))
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const lv_img_dsc_t ui_reference_img = {')
[void]$sb.AppendLine('    .header = {')
[void]$sb.AppendLine(('        .cf = {0},' -f $cf))
[void]$sb.AppendLine('        .always_zero = 0,')
[void]$sb.AppendLine('        .reserved = 0,')
[void]$sb.AppendLine(('        .w = {0},' -f $w))
[void]$sb.AppendLine(('        .h = {0},' -f $h))
[void]$sb.AppendLine('    },')
[void]$sb.AppendLine(('    .data_size = {0},' -f $dataSize))
[void]$sb.AppendLine(('    .data = {0},' -f $varName))
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')

$dir = Split-Path $OutC -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($OutC, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ('Wrote {0} ({1} bytes image data)' -f $OutC, $dataSize)
