// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef _WITE_THERMOSTAT_UI_H
#define _WITE_THERMOSTAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pymary_2fin_png);    // assets/PYMARY 2FIN.png
LV_IMG_DECLARE(ui_img_chatgpt_ak_png);    // assets/ChatGPT AK.png
LV_IMG_DECLARE(ui_img_optinos_fine_png);    // assets/OPTINOS FINE.png
LV_IMG_DECLARE(ui_img_secondary_fine_png);    // assets/SECONDARY FINE.png

// FONTS
LV_FONT_DECLARE(ui_font_BigTemp12);
LV_FONT_DECLARE(ui_font_BigTemp123);
LV_FONT_DECLARE(ui_font_BigTemp1234);
LV_FONT_DECLARE(ui_font_BigTemp22);
LV_FONT_DECLARE(ui_font_BigTemp221);
LV_FONT_DECLARE(ui_font_BigTemp221a);
LV_FONT_DECLARE(ui_font_Font100);
LV_FONT_DECLARE(ui_font_Font110);
LV_FONT_DECLARE(ui_font_Font36);
LV_FONT_DECLARE(ui_font_Font_10);
LV_FONT_DECLARE(ui_font_Font_105);
LV_FONT_DECLARE(ui_font_Font_110);
LV_FONT_DECLARE(ui_font_Font_12);
LV_FONT_DECLARE(ui_font_Font_120);
LV_FONT_DECLARE(ui_font_Font_15);
LV_FONT_DECLARE(ui_font_Font_18);
LV_FONT_DECLARE(ui_font_Font_20);
LV_FONT_DECLARE(ui_font_Font_26);
LV_FONT_DECLARE(ui_font_Font_40);
LV_FONT_DECLARE(ui_font_Font_50);
LV_FONT_DECLARE(ui_font_Font_55);
LV_FONT_DECLARE(ui_font_Font_70);
LV_FONT_DECLARE(ui_font_Font_85);
LV_FONT_DECLARE(ui_font_Font_92);
LV_FONT_DECLARE(ui_font_Font_94);
LV_FONT_DECLARE(ui_font_Font_95);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
