// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ROMEOS1_H
#define UI_ROMEOS1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Romeos1
extern void ui_Romeos1_screen_init(void);
extern void ui_Romeos1_screen_destroy(void);
extern lv_obj_t * ui_Romeos1;
extern lv_obj_t * ui_CenterC;
extern lv_obj_t * ui_Room;
extern lv_obj_t * ui_LabelO;
extern lv_obj_t * ui_LabelO1;
extern lv_obj_t * ui_LabelO2;
extern lv_obj_t * ui_Out;
extern lv_obj_t * ui_Solar;
extern lv_obj_t * ui_solarO;
extern lv_obj_t * ui_Solar2;
extern lv_obj_t * ui_Boiler;
extern lv_obj_t * ui_boilerO2;
extern lv_obj_t * ui_Boiler3;
extern lv_obj_t * ui_Intel2;
extern lv_obj_t * ui_intelO3;
extern lv_obj_t * ui_Boiler2;
extern lv_obj_t * ui_Outlet3;
extern lv_obj_t * ui_outletO2;
extern lv_obj_t * ui_autlet4;
extern lv_obj_t * ui_BOILE2;
extern lv_obj_t * ui_BOILE4;
extern lv_obj_t * ui_room8;
extern lv_obj_t * ui_room2;
extern lv_obj_t * ui_LabelPlin;
extern lv_obj_t * ui_LabelSin;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_room3;
extern lv_obj_t * ui_room4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

