// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_BigTemp12);
LV_FONT_DECLARE(ui_font_BigTemp123);
LV_FONT_DECLARE(ui_font_BigTemp1234);
LV_FONT_DECLARE(ui_font_BigTemp22);
LV_FONT_DECLARE(ui_font_BigTemp221);
LV_FONT_DECLARE(ui_font_BigTemp221a);
LV_FONT_DECLARE(ui_font_BigTemp221d);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
