// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: New Dysplay

#ifndef _NEW_DYSPLAY_UI_H
#define _NEW_DYSPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_THERMOSTAT_3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_chatgpt_az_png);    // assets/ChatGPT AZ.png
LV_IMG_DECLARE(ui_img_476397486);    // assets/icons8-partly-cloudy-day-100.png
LV_IMG_DECLARE(ui_img_1341533945);    // assets/icons8-pendant-light-100.png
LV_IMG_DECLARE(ui_img_313400180);    // assets/icons8-jalousie-100.png
LV_IMG_DECLARE(ui_img_54340154);    // assets/icons8-clock-100.png
LV_IMG_DECLARE(ui_img_1311305648);    // assets/icons8-alarm-100 (2).png
LV_IMG_DECLARE(ui_img_1757177593);    // assets/wifi-signal.png
LV_IMG_DECLARE(ui_img_962555020);    // assets/icons8-heating-room-100.png
LV_IMG_DECLARE(ui_img_589449191);    // assets/noun-ac-outer-3498295.png
LV_IMG_DECLARE(ui_img_359196471);    // assets/icons8-home-100 (1).png

// FONTS
LV_FONT_DECLARE(ui_font_BigTemp12);
LV_FONT_DECLARE(ui_font_BigTemp123);
LV_FONT_DECLARE(ui_font_BigTemp1234);
LV_FONT_DECLARE(ui_font_BigTemp22);
LV_FONT_DECLARE(ui_font_BigTemp221);
LV_FONT_DECLARE(ui_font_BigTemp221a);
LV_FONT_DECLARE(ui_font_Font100);
LV_FONT_DECLARE(ui_font_Font110);
LV_FONT_DECLARE(ui_font_Font_40);
LV_FONT_DECLARE(ui_font_Font_26);
LV_FONT_DECLARE(ui_font_Font_10);
LV_FONT_DECLARE(ui_font_Font_20);
LV_FONT_DECLARE(ui_font_Font_15);
LV_FONT_DECLARE(ui_font_Font_12);
LV_FONT_DECLARE(ui_font_Font_55);
LV_FONT_DECLARE(ui_font_Font_70);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
