// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_Screen6_screen_relocalize(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Label108;
extern lv_obj_t * ui_Label109;
extern lv_obj_t * ui_Label113;
extern lv_obj_t * ui_Label114;
extern lv_obj_t * ui_Label115;
extern lv_obj_t * ui_Label116;
extern lv_obj_t * ui_Label117;
extern lv_obj_t * ui_Label118;
extern lv_obj_t * ui_Label119;
extern lv_obj_t * ui_Label120;
extern lv_obj_t * ui_Label121;
extern lv_obj_t * ui_Label122;
extern void ui_event_OPTIONS5(lv_event_t * e);
extern lv_obj_t * ui_OPTIONS5;
extern lv_obj_t * ui_Label123;
extern lv_obj_t * ui_Label124;
extern lv_obj_t * ui_Label125;
extern lv_obj_t * ui_microphone4;
extern lv_obj_t * ui_Label126;
extern lv_obj_t * ui_Label127;
extern lv_obj_t * ui_Label128;
extern lv_obj_t * ui_Label129;
extern lv_obj_t * ui_Label130;
extern lv_obj_t * ui_Label131;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

