// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_Screen1_screen_relocalize(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label4;
extern void ui_event_OPTIONS(lv_event_t * e);
extern lv_obj_t * ui_OPTIONS;
extern lv_obj_t * ui_PLUS;
extern lv_obj_t * ui_MINUS;
extern lv_obj_t * ui_Label110;
extern lv_obj_t * ui_Label111;
extern lv_obj_t * ui_Label112;
extern lv_obj_t * ui_ALARM;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

