// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_Screen4_screen_relocalize(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Label75;
extern lv_obj_t * ui_Label76;
extern void ui_event_OPTIONS3(lv_event_t * e);
extern lv_obj_t * ui_OPTIONS3;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_Label79;
extern lv_obj_t * ui_microphone2;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_Label81;
extern lv_obj_t * ui_Label82;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_Label84;
extern lv_obj_t * ui_Label85;
extern lv_obj_t * ui_Label87;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

