// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_Screen5_screen_relocalize(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label86;
extern lv_obj_t * ui_Label88;
extern lv_obj_t * ui_Label89;
extern lv_obj_t * ui_Label90;
extern lv_obj_t * ui_Label91;
extern lv_obj_t * ui_Label92;
extern lv_obj_t * ui_Label93;
extern lv_obj_t * ui_Label94;
extern lv_obj_t * ui_Label95;
extern lv_obj_t * ui_Label96;
extern lv_obj_t * ui_Label97;
extern lv_obj_t * ui_Label98;
extern void ui_event_OPTIONS4(lv_event_t * e);
extern lv_obj_t * ui_OPTIONS4;
extern lv_obj_t * ui_Label99;
extern lv_obj_t * ui_Label100;
extern lv_obj_t * ui_Label101;
extern lv_obj_t * ui_microphone3;
extern lv_obj_t * ui_Label102;
extern lv_obj_t * ui_Label103;
extern lv_obj_t * ui_Label104;
extern lv_obj_t * ui_Label105;
extern lv_obj_t * ui_Label106;
extern lv_obj_t * ui_Label107;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

