// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_OPTIONS2 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_microphone1 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_Label63 = NULL;
lv_obj_t * ui_Label65 = NULL;
// event funtions
void ui_event_OPTIONS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_secondary_fine_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -274);
    lv_obj_set_y(ui_Label25, -196);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 273);
    lv_obj_set_y(ui_Label45, -196);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 335);
    lv_obj_set_y(ui_Label46, 113);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "5");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 320);
    lv_obj_set_y(ui_Label47, 113);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, ".");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 292);
    lv_obj_set_y(ui_Label48, 114);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "22");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -272);
    lv_obj_set_y(ui_Label49, 112);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "26");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -322);
    lv_obj_set_y(ui_Label50, -223);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "Wi-Fi Σπιτιου");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 321);
    lv_obj_set_y(ui_Label51, -223);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "Wi-Fi Λεβητα");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -40);
    lv_obj_set_y(ui_Label52, -208);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "21");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -9);
    lv_obj_set_y(ui_Label53, -212);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, ":");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 22);
    lv_obj_set_y(ui_Label54, -208);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "20");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 69);
    lv_obj_set_y(ui_Label55, -201);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "PM");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xCB9B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OPTIONS2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_OPTIONS2, 114);
    lv_obj_set_height(ui_OPTIONS2, 53);
    lv_obj_set_x(ui_OPTIONS2, 70);
    lv_obj_set_y(ui_OPTIONS2, 176);
    lv_obj_set_align(ui_OPTIONS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OPTIONS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OPTIONS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OPTIONS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OPTIONS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OPTIONS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OPTIONS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OPTIONS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OPTIONS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 354);
    lv_obj_set_y(ui_Label56, 102);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "O");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, 290);
    lv_obj_set_y(ui_Label57, 172);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "14");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 335);
    lv_obj_set_y(ui_Label58, 166);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "%");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_microphone1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_microphone1, 128);
    lv_obj_set_height(ui_microphone1, 60);
    lv_obj_set_x(ui_microphone1, -68);
    lv_obj_set_y(ui_microphone1, 176);
    lv_obj_set_align(ui_microphone1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_microphone1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_microphone1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_microphone1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_microphone1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_microphone1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_microphone1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_microphone1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_microphone1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_microphone1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_microphone1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, -238);
    lv_obj_set_y(ui_Label59, 112);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, ".");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -218);
    lv_obj_set_y(ui_Label60, 112);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "8");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -198);
    lv_obj_set_y(ui_Label61, 97);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "o");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, -259);
    lv_obj_set_y(ui_Label62, 172);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "58");
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -216);
    lv_obj_set_y(ui_Label63, 166);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "%");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -1);
    lv_obj_set_y(ui_Label65, -16);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "ΘΕΡΜΑΝΣΗ");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OPTIONS2, ui_event_OPTIONS2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label25 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;
    ui_Label47 = NULL;
    ui_Label48 = NULL;
    ui_Label49 = NULL;
    ui_Label50 = NULL;
    ui_Label51 = NULL;
    ui_Label52 = NULL;
    ui_Label53 = NULL;
    ui_Label54 = NULL;
    ui_Label55 = NULL;
    ui_OPTIONS2 = NULL;
    ui_Label56 = NULL;
    ui_Label57 = NULL;
    ui_Label58 = NULL;
    ui_microphone1 = NULL;
    ui_Label59 = NULL;
    ui_Label60 = NULL;
    ui_Label61 = NULL;
    ui_Label62 = NULL;
    ui_Label63 = NULL;
    ui_Label65 = NULL;

}

void ui_Screen3_screen_relocalize(void)
{
    // label widgets on screen

}
