// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    /* Default theme adds lv_btn PRESSED: color filter + grow + transitions (lv_theme_default.c) — those
       styles win over later lv_obj_set_style_* on the same selector, so "strip" in app code can look like
       a no-op. Basic theme only tags buttons with a single MAIN style and does not add PRESSED visuals. */
#if LV_USE_THEME_BASIC
    lv_theme_t * theme = lv_theme_basic_init(dispp);
#else
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
#endif
    lv_disp_set_theme(dispp, theme);
    ui_THERMOSTAT_1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_THERMOSTAT_1);
}

void ui_destroy(void)
{
    ui_THERMOSTAT_1_screen_destroy();
}
