// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if __has_include("lvgl.h")
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_THERMOSTAT_1.h"

///////////////////// VARIABLES ////////////////////

/* Compatibility aliases for existing runtime bindings */
#define ui_Button3 ui_LIGHTS
#define ui_Button4 ui_HEAT_PUMP
#define ui_Button6 ui_ALARM
#define ui_Button7 ui_Button_MINUS
#define ui_Button8 ui_Button_PLUS
#define ui_Button9 ui_Button_CLOCK_LEFT
#define ui_Button10 ui_Button_CLOCK_RIGHT


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_thermostat_a_png);    // assets/THermostat A.png
LV_IMG_DECLARE(ui_img_thermostat_ab_png);    // assets/THermostat AB.png
LV_IMG_DECLARE(ui_img_hot_png);
LV_IMG_DECLARE(ui_img_col_png);
LV_IMG_DECLARE(ui_img_chatgpt1_32x32_png);
LV_IMG_DECLARE(ui_img_chatgpt111111_png);    // assets/ChatGPT111111.png
LV_IMG_DECLARE(ui_img_ring_template_png);    // assets/ring_template.png
LV_IMG_DECLARE(ui_img_1757177593);    // assets/wifi-signal.png
LV_IMG_DECLARE(ui_img_day_p0);    // 5 Ikones: 23.00-6.00
LV_IMG_DECLARE(ui_img_day_p1);    // 5 Ikones: 6.00-8.00
LV_IMG_DECLARE(ui_img_day_p2);    // 5 Ikones: 8.00-17.00
LV_IMG_DECLARE(ui_img_day_p3);    // 5 Ikones: 17.00-20.00
LV_IMG_DECLARE(ui_img_day_p4);    // 5 Ikones: 20.00-23.00

// FONTS
LV_FONT_DECLARE(ui_font_BigTemp12);
LV_FONT_DECLARE(ui_font_BigTemp123);
LV_FONT_DECLARE(ui_font_BigTemp1234);
LV_FONT_DECLARE(ui_font_BigTemp22);
LV_FONT_DECLARE(ui_font_BigTemp221);
LV_FONT_DECLARE(ui_font_BigTemp221a);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
