// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Label108 = NULL;
lv_obj_t * ui_Label109 = NULL;
lv_obj_t * ui_Label113 = NULL;
lv_obj_t * ui_Label114 = NULL;
lv_obj_t * ui_Label115 = NULL;
lv_obj_t * ui_Label116 = NULL;
lv_obj_t * ui_Label117 = NULL;
lv_obj_t * ui_Label118 = NULL;
lv_obj_t * ui_Label119 = NULL;
lv_obj_t * ui_Label120 = NULL;
lv_obj_t * ui_Label121 = NULL;
lv_obj_t * ui_Label122 = NULL;
lv_obj_t * ui_OPTIONS5 = NULL;
lv_obj_t * ui_Label123 = NULL;
lv_obj_t * ui_Label124 = NULL;
lv_obj_t * ui_Label125 = NULL;
lv_obj_t * ui_ALARM5 = NULL;
lv_obj_t * ui_Label126 = NULL;
lv_obj_t * ui_Label127 = NULL;
lv_obj_t * ui_Label128 = NULL;
lv_obj_t * ui_Label129 = NULL;
lv_obj_t * ui_Label130 = NULL;
lv_obj_t * ui_Label131 = NULL;
// event funtions
void ui_event_OPTIONS5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen6, &ui_img_secondary_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label108 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label108, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label108, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label108, -273);
    lv_obj_set_y(ui_Label108, -196);
    lv_obj_set_align(ui_Label108, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label108, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label108, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label108, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label108, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label109 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label109, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label109, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label109, 273);
    lv_obj_set_y(ui_Label109, -196);
    lv_obj_set_align(ui_Label109, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label109, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label109, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label109, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label109, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label113 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label113, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label113, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label113, 335);
    lv_obj_set_y(ui_Label113, 113);
    lv_obj_set_align(ui_Label113, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label113, "5");
    lv_obj_set_style_text_color(ui_Label113, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label113, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label113, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label114 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label114, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label114, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label114, 320);
    lv_obj_set_y(ui_Label114, 113);
    lv_obj_set_align(ui_Label114, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label114, ".");
    lv_obj_set_style_text_color(ui_Label114, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label114, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label114, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label115 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label115, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label115, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label115, 292);
    lv_obj_set_y(ui_Label115, 114);
    lv_obj_set_align(ui_Label115, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label115, "22");
    lv_obj_set_style_text_color(ui_Label115, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label115, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label115, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label116 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label116, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label116, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label116, -272);
    lv_obj_set_y(ui_Label116, 112);
    lv_obj_set_align(ui_Label116, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label116, "26");
    lv_obj_set_style_text_color(ui_Label116, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label116, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label116, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label117 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label117, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label117, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label117, -322);
    lv_obj_set_y(ui_Label117, -223);
    lv_obj_set_align(ui_Label117, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label117, "Wi-Fi Σπιτιου");
    lv_obj_set_style_text_color(ui_Label117, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label117, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label117, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label118 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label118, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label118, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label118, 321);
    lv_obj_set_y(ui_Label118, -223);
    lv_obj_set_align(ui_Label118, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label118, "Wi-Fi Λεβητα");
    lv_obj_set_style_text_color(ui_Label118, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label118, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label118, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label119 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label119, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label119, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label119, -40);
    lv_obj_set_y(ui_Label119, -208);
    lv_obj_set_align(ui_Label119, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label119, "21");
    lv_obj_set_style_text_color(ui_Label119, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label119, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label119, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label120 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label120, -9);
    lv_obj_set_y(ui_Label120, -212);
    lv_obj_set_align(ui_Label120, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label120, ":");
    lv_obj_set_style_text_color(ui_Label120, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label120, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label120, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label121 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label121, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label121, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label121, 22);
    lv_obj_set_y(ui_Label121, -208);
    lv_obj_set_align(ui_Label121, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label121, "20");
    lv_obj_set_style_text_color(ui_Label121, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label121, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label121, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label122 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label122, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label122, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label122, 69);
    lv_obj_set_y(ui_Label122, -201);
    lv_obj_set_align(ui_Label122, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label122, "PM");
    lv_obj_set_style_text_color(ui_Label122, lv_color_hex(0xCB9B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label122, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label122, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OPTIONS5 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_OPTIONS5, 114);
    lv_obj_set_height(ui_OPTIONS5, 53);
    lv_obj_set_x(ui_OPTIONS5, 70);
    lv_obj_set_y(ui_OPTIONS5, 176);
    lv_obj_set_align(ui_OPTIONS5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OPTIONS5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OPTIONS5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OPTIONS5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OPTIONS5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OPTIONS5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OPTIONS5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OPTIONS5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OPTIONS5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label123 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label123, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label123, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label123, 354);
    lv_obj_set_y(ui_Label123, 102);
    lv_obj_set_align(ui_Label123, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label123, "O");
    lv_obj_set_style_text_color(ui_Label123, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label123, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label123, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label124 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label124, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label124, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label124, 290);
    lv_obj_set_y(ui_Label124, 172);
    lv_obj_set_align(ui_Label124, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label124, "14");
    lv_obj_set_style_text_color(ui_Label124, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label124, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label124, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label125 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label125, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label125, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label125, 335);
    lv_obj_set_y(ui_Label125, 166);
    lv_obj_set_align(ui_Label125, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label125, "%");
    lv_obj_set_style_text_color(ui_Label125, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label125, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label125, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ALARM5 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ALARM5, 128);
    lv_obj_set_height(ui_ALARM5, 60);
    lv_obj_set_x(ui_ALARM5, -68);
    lv_obj_set_y(ui_ALARM5, 176);
    lv_obj_set_align(ui_ALARM5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ALARM5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ALARM5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ALARM5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ALARM5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ALARM5, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ALARM5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ALARM5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ALARM5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ALARM5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ALARM5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label126 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label126, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label126, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label126, -238);
    lv_obj_set_y(ui_Label126, 112);
    lv_obj_set_align(ui_Label126, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label126, ".");
    lv_obj_set_style_text_color(ui_Label126, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label126, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label126, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label127 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label127, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label127, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label127, -218);
    lv_obj_set_y(ui_Label127, 112);
    lv_obj_set_align(ui_Label127, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label127, "8");
    lv_obj_set_style_text_color(ui_Label127, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label127, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label127, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label128 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label128, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label128, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label128, -198);
    lv_obj_set_y(ui_Label128, 97);
    lv_obj_set_align(ui_Label128, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label128, "o");
    lv_obj_set_style_text_color(ui_Label128, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label128, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label128, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label129 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label129, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label129, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label129, -259);
    lv_obj_set_y(ui_Label129, 172);
    lv_obj_set_align(ui_Label129, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label129, "58");
    lv_obj_set_style_text_color(ui_Label129, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label129, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label129, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label130 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label130, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label130, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label130, -216);
    lv_obj_set_y(ui_Label130, 166);
    lv_obj_set_align(ui_Label130, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label130, "%");
    lv_obj_set_style_text_color(ui_Label130, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label130, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label130, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label131 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label131, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label131, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label131, -1);
    lv_obj_set_y(ui_Label131, -16);
    lv_obj_set_align(ui_Label131, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label131, "ΡΟΛΑ");
    lv_obj_set_style_text_color(ui_Label131, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label131, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label131, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OPTIONS5, ui_event_OPTIONS5, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Label108 = NULL;
    ui_Label109 = NULL;
    ui_Label113 = NULL;
    ui_Label114 = NULL;
    ui_Label115 = NULL;
    ui_Label116 = NULL;
    ui_Label117 = NULL;
    ui_Label118 = NULL;
    ui_Label119 = NULL;
    ui_Label120 = NULL;
    ui_Label121 = NULL;
    ui_Label122 = NULL;
    ui_OPTIONS5 = NULL;
    ui_Label123 = NULL;
    ui_Label124 = NULL;
    ui_Label125 = NULL;
    ui_ALARM5 = NULL;
    ui_Label126 = NULL;
    ui_Label127 = NULL;
    ui_Label128 = NULL;
    ui_Label129 = NULL;
    ui_Label130 = NULL;
    ui_Label131 = NULL;

}

void ui_Screen6_screen_relocalize(void)
{
    // label widgets on screen

}
