// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_Screen2_screen_relocalize(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label24;
extern void ui_event_OPTIONS1(lv_event_t * e);
extern lv_obj_t * ui_OPTIONS1;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_ALARM1;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

