/* Auto-generated by scripts/measure_and_strip_center_21.ps1 - do not edit */
#ifndef UI_REFERENCE_MAIN_DIAL_MEASURE_H
#define UI_REFERENCE_MAIN_DIAL_MEASURE_H

#include <stdint.h>

/* Full bright text bbox (21 + degree) in px */
static const int16_t kUiMainDialTextLeft = 235;
static const int16_t kUiMainDialTextRight = 405;
static const int16_t kUiMainDialTextTop = 168;
static const int16_t kUiMainDialTextBottom = 302;
static const int16_t kUiMainDialTextHeight = 135;

/* Removed glyph ""2"" */
static const int16_t kUiMainDialG2Left = 235;
static const int16_t kUiMainDialG2Right = 291;
static const int16_t kUiMainDialG2CenterX = 263;
static const int16_t kUiMainDialG2Width = 57;

/* Removed glyph ""1"" */
static const int16_t kUiMainDialG1Left = 292;
static const int16_t kUiMainDialG1Right = 348;
static const int16_t kUiMainDialG1CenterX = 320;
static const int16_t kUiMainDialG1Width = 57;

/* Degree symbol (bitmap) */
static const int16_t kUiMainDialDegLeft = 349;
static const int16_t kUiMainDialDegRight = 405;
static const int16_t kUiMainDialDegCenterX = 377;
static const int16_t kUiMainDialDegWidth = 57;

/* LVGL integer setpoint: label top-left (Montserrat 48). Align right edge before degree. */
static const int16_t kUiMainDialSetpointLabelX = 235;
static const int16_t kUiMainDialSetpointLabelY = 168;
/* Target: label ends near x <= 345 (deg at 349, gap 4px) */

#endif

