// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_THERMOSTAT_1_H
#define UI_THERMOSTAT_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_THERMOSTAT_1
extern void ui_THERMOSTAT_1_screen_init(void);
extern void ui_THERMOSTAT_1_screen_destroy(void);
extern lv_obj_t * ui_THERMOSTAT_1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_HEATING;
extern lv_obj_t * ui_LIGHTS;
extern lv_obj_t * ui_HEAT_PUMP;
extern lv_obj_t * ui_BLINDS;
extern lv_obj_t * ui_ALARM;
extern lv_obj_t * ui_Button_MINUS;
extern lv_obj_t * ui_Button_PLUS;
extern lv_obj_t * ui_Button_CLOCK_LEFT;
extern lv_obj_t * ui_Button_CLOCK_RIGHT;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

