// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Romeos1 = NULL;
lv_obj_t * ui_CenterC = NULL;
lv_obj_t * ui_Room = NULL;
lv_obj_t * ui_LabelO = NULL;
lv_obj_t * ui_LabelO1 = NULL;
lv_obj_t * ui_LabelO2 = NULL;
lv_obj_t * ui_Out = NULL;
lv_obj_t * ui_Solar = NULL;
lv_obj_t * ui_solarO = NULL;
lv_obj_t * ui_Solar2 = NULL;
lv_obj_t * ui_Boiler = NULL;
lv_obj_t * ui_boilerO2 = NULL;
lv_obj_t * ui_Boiler3 = NULL;
lv_obj_t * ui_Intel2 = NULL;
lv_obj_t * ui_intelO3 = NULL;
lv_obj_t * ui_Boiler2 = NULL;
lv_obj_t * ui_Outlet3 = NULL;
lv_obj_t * ui_outletO2 = NULL;
lv_obj_t * ui_autlet4 = NULL;
lv_obj_t * ui_BOILE2 = NULL;
lv_obj_t * ui_BOILE4 = NULL;
lv_obj_t * ui_room8 = NULL;
lv_obj_t * ui_room2 = NULL;
lv_obj_t * ui_LabelPlin = NULL;
lv_obj_t * ui_LabelSin = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_room3 = NULL;
lv_obj_t * ui_room4 = NULL;
// event funtions

// build funtions

void ui_Romeos1_screen_init(void)
{
    ui_Romeos1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Romeos1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Romeos1, &ui_img_romeos_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CenterC = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_CenterC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CenterC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CenterC, 142);
    lv_obj_set_y(ui_CenterC, 138);
    lv_obj_set_flex_flow(ui_CenterC, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CenterC, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_CenterC, "24");
    lv_obj_set_style_text_color(ui_CenterC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CenterC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CenterC, &ui_font_BigTemp123, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Room, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Room, -326);
    lv_obj_set_y(ui_Room, -171);
    lv_obj_set_align(ui_Room, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Room, "21");
    lv_obj_set_style_text_color(ui_Room, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Room, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Room, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelO = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_LabelO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelO, -107);
    lv_obj_set_y(ui_LabelO, -101);
    lv_obj_set_align(ui_LabelO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelO, "O");
    lv_obj_set_style_text_color(ui_LabelO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelO, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelO1 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_LabelO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelO1, -291);
    lv_obj_set_y(ui_LabelO1, -191);
    lv_obj_set_align(ui_LabelO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelO1, "O");
    lv_obj_set_style_text_color(ui_LabelO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelO1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelO2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_LabelO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelO2, -8);
    lv_obj_set_y(ui_LabelO2, -189);
    lv_obj_set_align(ui_LabelO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelO2, "O");
    lv_obj_set_style_text_color(ui_LabelO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelO2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Out, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Out, -43);
    lv_obj_set_y(ui_Out, -168);
    lv_obj_set_align(ui_Out, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out, "17");
    lv_obj_set_style_text_color(ui_Out, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Solar = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Solar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Solar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Solar, 116);
    lv_obj_set_y(ui_Solar, -116);
    lv_obj_set_align(ui_Solar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Solar, "87");
    lv_obj_set_style_text_color(ui_Solar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Solar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Solar, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_solarO = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_solarO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_solarO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_solarO, 157);
    lv_obj_set_y(ui_solarO, -127);
    lv_obj_set_align(ui_solarO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_solarO, "O");
    lv_obj_set_style_text_color(ui_solarO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_solarO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_solarO, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Solar2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Solar2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Solar2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Solar2, 288);
    lv_obj_set_y(ui_Solar2, -117);
    lv_obj_set_align(ui_Solar2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Solar2, "SOLAR");
    lv_obj_set_style_text_color(ui_Solar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Solar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Solar2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boiler = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Boiler, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Boiler, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Boiler, 114);
    lv_obj_set_y(ui_Boiler, -47);
    lv_obj_set_align(ui_Boiler, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Boiler, "64");
    lv_obj_set_style_text_color(ui_Boiler, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Boiler, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Boiler, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boilerO2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_boilerO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boilerO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boilerO2, 157);
    lv_obj_set_y(ui_boilerO2, -58);
    lv_obj_set_align(ui_boilerO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_boilerO2, "O");
    lv_obj_set_style_text_color(ui_boilerO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boilerO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boilerO2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boiler3 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Boiler3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Boiler3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Boiler3, 282);
    lv_obj_set_y(ui_Boiler3, -48);
    lv_obj_set_align(ui_Boiler3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Boiler3, "BOILER");
    lv_obj_set_style_text_color(ui_Boiler3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Boiler3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Boiler3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Intel2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Intel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Intel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Intel2, 113);
    lv_obj_set_y(ui_Intel2, 22);
    lv_obj_set_align(ui_Intel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Intel2, "40");
    lv_obj_set_style_text_color(ui_Intel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Intel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Intel2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_intelO3 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_intelO3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_intelO3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_intelO3, 157);
    lv_obj_set_y(ui_intelO3, 12);
    lv_obj_set_align(ui_intelO3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_intelO3, "O");
    lv_obj_set_style_text_color(ui_intelO3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intelO3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intelO3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boiler2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Boiler2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Boiler2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Boiler2, 295);
    lv_obj_set_y(ui_Boiler2, 23);
    lv_obj_set_align(ui_Boiler2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Boiler2, "INTEL");
    lv_obj_set_style_text_color(ui_Boiler2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Boiler2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Boiler2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Outlet3 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Outlet3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Outlet3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Outlet3, 110);
    lv_obj_set_y(ui_Outlet3, 91);
    lv_obj_set_align(ui_Outlet3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Outlet3, "34");
    lv_obj_set_style_text_color(ui_Outlet3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Outlet3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Outlet3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outletO2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_outletO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outletO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outletO2, 155);
    lv_obj_set_y(ui_outletO2, 80);
    lv_obj_set_align(ui_outletO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outletO2, "O");
    lv_obj_set_style_text_color(ui_outletO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outletO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outletO2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autlet4 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_autlet4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autlet4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autlet4, 274);
    lv_obj_set_y(ui_autlet4, 93);
    lv_obj_set_align(ui_autlet4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autlet4, "OUTLET");
    lv_obj_set_style_text_color(ui_autlet4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autlet4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autlet4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BOILE2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_BOILE2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BOILE2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BOILE2, 115);
    lv_obj_set_y(ui_BOILE2, 161);
    lv_obj_set_align(ui_BOILE2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BOILE2, "ON");
    lv_obj_set_style_text_color(ui_BOILE2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BOILE2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BOILE2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BOILE4 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_BOILE4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BOILE4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BOILE4, 279);
    lv_obj_set_y(ui_BOILE4, 161);
    lv_obj_set_align(ui_BOILE4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BOILE4, "BOILER");
    lv_obj_set_style_text_color(ui_BOILE4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BOILE4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BOILE4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_room8 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_room8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_room8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_room8, -326);
    lv_obj_set_y(ui_room8, -140);
    lv_obj_set_align(ui_room8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_room8, "ROOM");
    lv_obj_set_style_text_color(ui_room8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_room8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_room8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_room2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_room2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_room2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_room2, -46);
    lv_obj_set_y(ui_room2, -138);
    lv_obj_set_align(ui_room2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_room2, "OUT");
    lv_obj_set_style_text_color(ui_room2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_room2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_room2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPlin = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_LabelPlin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPlin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPlin, -339);
    lv_obj_set_y(ui_LabelPlin, 168);
    lv_obj_set_align(ui_LabelPlin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPlin, "-");
    lv_obj_set_style_text_color(ui_LabelPlin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPlin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPlin, &ui_font_BigTemp221a, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSin = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_LabelSin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSin, -256);
    lv_obj_set_y(ui_LabelSin, 175);
    lv_obj_set_align(ui_LabelSin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSin, "+");
    lv_obj_set_style_text_color(ui_LabelSin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSin, &ui_font_BigTemp221a, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image2, &ui_img_1757177593);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -29);
    lv_obj_set_y(ui_Image2, 49);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 400);
    /* Romeos: στατικό PNG — κρυφό (το σήμα είναι δυναμικό τόξο στο main.cpp) */
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);

    ui_Image5 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image5, &ui_img_sync_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 114);
    lv_obj_set_y(ui_Image5, -194);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 280);

    ui_Image3 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image3, &ui_img_sync_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 214);
    lv_obj_set_y(ui_Image3, -194);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 280);

    ui_Image4 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image4, &ui_img_sync_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 314);
    lv_obj_set_y(ui_Image4, -194);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 280);

    ui_Label10 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 213);
    lv_obj_set_y(ui_Label10, -195);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "1");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 313);
    lv_obj_set_y(ui_Label2, -195);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "2");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image6, &ui_img_306578094);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 113);
    lv_obj_set_y(ui_Image6, -195);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 370);

    ui_Image7 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image7, &ui_img_emergency_12_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -176);
    lv_obj_set_y(ui_Image7, 171);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 350);

    ui_Image8 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image8, &ui_img_388382192);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -94);
    lv_obj_set_y(ui_Image8, 172);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 150);

    ui_Image9 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image9, &ui_img_891469010);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -12);
    lv_obj_set_y(ui_Image9, 172);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 150);

    ui_Label11 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -240);
    lv_obj_set_y(ui_Label11, 21);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "23");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -212);
    lv_obj_set_y(ui_Label12, 20);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, ":");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -182);
    lv_obj_set_y(ui_Label13, 21);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "28");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -126);
    lv_obj_set_y(ui_Label3, 22);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PM");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Romeos1);
    lv_img_set_src(ui_Image10, &ui_img_1757177593);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -324);
    lv_obj_set_y(ui_Image10, 51);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 400);
    /* Romeos: στατικό PNG HOME κρυφό — τόξα από main.cpp */
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_HIDDEN);

    ui_room3 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_room3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_room3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_room3, -324);
    lv_obj_set_y(ui_room3, 87);
    lv_obj_set_align(ui_room3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_room3, "HOME");
    lv_obj_set_style_text_color(ui_room3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_room3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_room3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_room4 = lv_label_create(ui_Romeos1);
    lv_obj_set_width(ui_room4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_room4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_room4, -32);
    lv_obj_set_y(ui_room4, 87);
    lv_obj_set_align(ui_room4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_room4, "ESP32");
    lv_obj_set_style_text_color(ui_room4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_room4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_room4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Romeos1_screen_destroy(void)
{
    if(ui_Romeos1) lv_obj_del(ui_Romeos1);

    // NULL screen variables
    ui_Romeos1 = NULL;
    ui_CenterC = NULL;
    ui_Room = NULL;
    ui_LabelO = NULL;
    ui_LabelO1 = NULL;
    ui_LabelO2 = NULL;
    ui_Out = NULL;
    ui_Solar = NULL;
    ui_solarO = NULL;
    ui_Solar2 = NULL;
    ui_Boiler = NULL;
    ui_boilerO2 = NULL;
    ui_Boiler3 = NULL;
    ui_Intel2 = NULL;
    ui_intelO3 = NULL;
    ui_Boiler2 = NULL;
    ui_Outlet3 = NULL;
    ui_outletO2 = NULL;
    ui_autlet4 = NULL;
    ui_BOILE2 = NULL;
    ui_BOILE4 = NULL;
    ui_room8 = NULL;
    ui_room2 = NULL;
    ui_LabelPlin = NULL;
    ui_LabelSin = NULL;
    ui_Image2 = NULL;
    ui_Image5 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Label10 = NULL;
    ui_Label2 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label3 = NULL;
    ui_Image10 = NULL;
    ui_room3 = NULL;
    ui_room4 = NULL;

}
