// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: WITE THERMOSTAT

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Label86 = NULL;
lv_obj_t * ui_Label88 = NULL;
lv_obj_t * ui_Label89 = NULL;
lv_obj_t * ui_Label90 = NULL;
lv_obj_t * ui_Label91 = NULL;
lv_obj_t * ui_Label92 = NULL;
lv_obj_t * ui_Label93 = NULL;
lv_obj_t * ui_Label94 = NULL;
lv_obj_t * ui_Label95 = NULL;
lv_obj_t * ui_Label96 = NULL;
lv_obj_t * ui_Label97 = NULL;
lv_obj_t * ui_Label98 = NULL;
lv_obj_t * ui_OPTIONS4 = NULL;
lv_obj_t * ui_Label99 = NULL;
lv_obj_t * ui_Label100 = NULL;
lv_obj_t * ui_Label101 = NULL;
lv_obj_t * ui_ALARM4 = NULL;
lv_obj_t * ui_Label102 = NULL;
lv_obj_t * ui_Label103 = NULL;
lv_obj_t * ui_Label104 = NULL;
lv_obj_t * ui_Label105 = NULL;
lv_obj_t * ui_Label106 = NULL;
lv_obj_t * ui_Label107 = NULL;
// event funtions
void ui_event_OPTIONS4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen5, &ui_img_secondary_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label86 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label86, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label86, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label86, -274);
    lv_obj_set_y(ui_Label86, -196);
    lv_obj_set_align(ui_Label86, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label86, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label86, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label86, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label88, 273);
    lv_obj_set_y(ui_Label88, -196);
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, "Συνδεδεμενο");
    lv_obj_set_style_text_color(ui_Label88, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label88, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label88, &ui_font_Font_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label89 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label89, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label89, 335);
    lv_obj_set_y(ui_Label89, 113);
    lv_obj_set_align(ui_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label89, "5");
    lv_obj_set_style_text_color(ui_Label89, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label89, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label89, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label90 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label90, 320);
    lv_obj_set_y(ui_Label90, 113);
    lv_obj_set_align(ui_Label90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label90, ".");
    lv_obj_set_style_text_color(ui_Label90, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label90, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label91, 292);
    lv_obj_set_y(ui_Label91, 114);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, "22");
    lv_obj_set_style_text_color(ui_Label91, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label91, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label91, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label92, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label92, -272);
    lv_obj_set_y(ui_Label92, 112);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "26");
    lv_obj_set_style_text_color(ui_Label92, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label92, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label92, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label93 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label93, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label93, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label93, -324);
    lv_obj_set_y(ui_Label93, -223);
    lv_obj_set_align(ui_Label93, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label93, "Wi-Fi Σπιτιου");
    lv_obj_set_style_text_color(ui_Label93, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label93, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label93, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label94 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label94, 321);
    lv_obj_set_y(ui_Label94, -223);
    lv_obj_set_align(ui_Label94, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label94, "Wi-Fi Λεβητα");
    lv_obj_set_style_text_color(ui_Label94, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label94, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label94, &ui_font_Font_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label95 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label95, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label95, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label95, -40);
    lv_obj_set_y(ui_Label95, -208);
    lv_obj_set_align(ui_Label95, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label95, "21");
    lv_obj_set_style_text_color(ui_Label95, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label95, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label95, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label96 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label96, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label96, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label96, -9);
    lv_obj_set_y(ui_Label96, -212);
    lv_obj_set_align(ui_Label96, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label96, ":");
    lv_obj_set_style_text_color(ui_Label96, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label96, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label96, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label97 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label97, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label97, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label97, 22);
    lv_obj_set_y(ui_Label97, -208);
    lv_obj_set_align(ui_Label97, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label97, "20");
    lv_obj_set_style_text_color(ui_Label97, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label97, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label97, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label98 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label98, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label98, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label98, 69);
    lv_obj_set_y(ui_Label98, -201);
    lv_obj_set_align(ui_Label98, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label98, "PM");
    lv_obj_set_style_text_color(ui_Label98, lv_color_hex(0xCB9B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label98, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label98, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OPTIONS4 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_OPTIONS4, 114);
    lv_obj_set_height(ui_OPTIONS4, 53);
    lv_obj_set_x(ui_OPTIONS4, 70);
    lv_obj_set_y(ui_OPTIONS4, 176);
    lv_obj_set_align(ui_OPTIONS4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OPTIONS4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OPTIONS4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OPTIONS4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OPTIONS4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OPTIONS4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OPTIONS4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OPTIONS4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OPTIONS4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label99 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label99, 354);
    lv_obj_set_y(ui_Label99, 102);
    lv_obj_set_align(ui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label99, "O");
    lv_obj_set_style_text_color(ui_Label99, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label99, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, 290);
    lv_obj_set_y(ui_Label100, 172);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "14");
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label100, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label101 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label101, 335);
    lv_obj_set_y(ui_Label101, 166);
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "%");
    lv_obj_set_style_text_color(ui_Label101, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label101, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ALARM4 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ALARM4, 128);
    lv_obj_set_height(ui_ALARM4, 60);
    lv_obj_set_x(ui_ALARM4, -68);
    lv_obj_set_y(ui_ALARM4, 176);
    lv_obj_set_align(ui_ALARM4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ALARM4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ALARM4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ALARM4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ALARM4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ALARM4, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ALARM4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ALARM4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ALARM4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ALARM4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ALARM4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label102, -238);
    lv_obj_set_y(ui_Label102, 112);
    lv_obj_set_align(ui_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label102, ".");
    lv_obj_set_style_text_color(ui_Label102, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label102, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label103 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label103, -218);
    lv_obj_set_y(ui_Label103, 112);
    lv_obj_set_align(ui_Label103, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label103, "8");
    lv_obj_set_style_text_color(ui_Label103, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label103, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label104, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label104, -198);
    lv_obj_set_y(ui_Label104, 97);
    lv_obj_set_align(ui_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label104, "o");
    lv_obj_set_style_text_color(ui_Label104, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label104, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label104, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label105 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label105, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label105, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label105, -259);
    lv_obj_set_y(ui_Label105, 172);
    lv_obj_set_align(ui_Label105, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label105, "58");
    lv_obj_set_style_text_color(ui_Label105, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label105, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label105, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label106 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label106, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label106, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label106, -216);
    lv_obj_set_y(ui_Label106, 166);
    lv_obj_set_align(ui_Label106, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label106, "%");
    lv_obj_set_style_text_color(ui_Label106, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label106, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label106, &ui_font_Font_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label107 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label107, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label107, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label107, -1);
    lv_obj_set_y(ui_Label107, -16);
    lv_obj_set_align(ui_Label107, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label107, "ΡΟΛΑ");
    lv_obj_set_style_text_color(ui_Label107, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label107, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label107, &ui_font_Font_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OPTIONS4, ui_event_OPTIONS4, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Label86 = NULL;
    ui_Label88 = NULL;
    ui_Label89 = NULL;
    ui_Label90 = NULL;
    ui_Label91 = NULL;
    ui_Label92 = NULL;
    ui_Label93 = NULL;
    ui_Label94 = NULL;
    ui_Label95 = NULL;
    ui_Label96 = NULL;
    ui_Label97 = NULL;
    ui_Label98 = NULL;
    ui_OPTIONS4 = NULL;
    ui_Label99 = NULL;
    ui_Label100 = NULL;
    ui_Label101 = NULL;
    ui_ALARM4 = NULL;
    ui_Label102 = NULL;
    ui_Label103 = NULL;
    ui_Label104 = NULL;
    ui_Label105 = NULL;
    ui_Label106 = NULL;
    ui_Label107 = NULL;

}

void ui_Screen5_screen_relocalize(void)
{
    // label widgets on screen

}
